### ISSUE TITLE
Citation info please

### ISSUE THREAD

**Issue by lonelyjoeparker** [ggautreau/PPanGGOLiN#1]
Great package and really interesting work (saw you at GI2018 in Sanger)

Is there a citation for the package and/or example dataset please?

**Comment by ggautreau** [comment]
Hi,

Thank you.

We plan to publish PPanGGOLiN during the early 2019. I am currently working on the improvement of some aspects, like the extraction of path, partitioning with more than 3 partitions, improving the metadata association....

You can test PPanGGOLiN using our toy example (C. trachomatis) in the directory `testing_dataset_C_trachomatis` using this command : 
`ppanggolin --organisms testing_dataset_C_trachomatis/orgs.list --gene_families testing_dataset_C_trachomatis/families.tsv`

For the moment, you can only cite the github URL or the GI conference.

Guillaume.

**Comment by lonelyjoeparker** [comment]
Hi Guillaume thanks very much for that. Maybe worth adding a section to the [README](https://github.com/ggautreau/PPanGGOLiN/README.md)?

**Comment by ggautreau** [comment]
Yes, i agree
